# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20180113_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='1.jpg', upload_to='bg_pics'),
        ),
    ]
