# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='1.jpg', upload_to=''),
        ),
    ]
